version: '3'

services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123qweasd
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/log:/var/log/mysql
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./docker/grafana:/var/lib/grafana'
    environment:
      - HTTP_USER="admin"
      - HTTP_PASS="123qweasd"
      - MYSQL_HOST=db
      - MYSQL_PORT=8086
      - MYSQL_NAME="kotel"
      - MYSQL_USER="root"
      - MYSQL_PASS="123qweasd"
    restart: always
